package org.example;

import java.util.*;
import java.lang.*;


public class NumberGame {
    int guesses = 0;
    int score = 0;


    public NumberGame(int guesses, int score) {
        this.guesses = guesses;
        this.score = score;
    }


    // This method starts the game and generates a random number from 1 to 10.
    public void startGame() {
        guesses = 3;

        System.out.println("Welcome to the Number Game!");
        System.out.println("The computer will generate a random number from 1 to 10. Can you guess what it is?");

        int min = 1;
        int max = 10;
        int randomNum = min + (int) (Math.random() * ((max - min) + 1));

        getUserGuess(randomNum, guesses);
    }


    /**
     * This method checks that the user still has remaining attempts before prompting the user to enter their guess for the generated number. Then it compares the user's guess with the generated number and provides feedback on whether the guess is too low, too high, or correct. If the user's guess is incorrect, it will repeat until the user guesses the correct number or runs out of remaining attempts before asking if they want to play again. If the user's guess is correct, it will also display their score, which is based on the number of attempts taken or rounds won.
     *
     * @param randomNum represents the random number generated by the computer
     * @param guesses represents the number of guesses the user has still remaining
     */
    public void getUserGuess(int randomNum, int guesses) {
        if (guesses >= 1) {
            System.out.println("Enter your guess.");

            Scanner guessScanner = new Scanner(System.in);
            int guessInput = guessScanner.nextInt();

            guesses--;

            if (guessInput < randomNum) {
                System.out.println("Too low! Guesses left: " + guesses);
                getUserGuess(randomNum, guesses);
            } else if (guessInput > randomNum) {
                System.out.println("Too high! Guesses left: " + guesses);
                getUserGuess(randomNum, guesses);
            } else {
                score++;
                System.out.println("That's correct! Here's your score: " + score);
                System.out.println("Would you like to play again? Enter 'Y' or 'N'.");
                playAgain();
            }
        } else {
            System.out.println("Sorry, you have no more guesses remaining. Game over!");
            System.out.println("Would you like to play again? Enter 'Y' or 'N'.");
            playAgain();
        }
    }


    // This method checks that the user's input is valid and determines if they want to play again. If so, it will restart the game.
    public void playAgain() {
        Scanner playScanner = new Scanner(System.in);
        String playInput = playScanner.nextLine();

        if (playInput.equalsIgnoreCase("Y")) {
            startGame();
        } else if (playInput.equalsIgnoreCase("N")) {
            System.out.println("Ok, thanks for playing!");
        } else {
            System.out.println("Please enter 'Y' or 'N'.");
            playAgain();
        }
    }
}
